// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"time"
)

// Injectors from wire.go:

func InitService() Service {
	deps := ProvideDeps()
	service := ProvideService(deps)
	return service
}

func InitAnotherService() AnotherService {
	deps := ProvideDeps()
	anotherService := ProvideAnotherService(deps)
	return anotherService
}

// wire.go:

// ProvideDeps ...
func ProvideDeps() *Deps {
	return &Deps{
		date: time.Now(),
	}
}

// ProvideService ...
func ProvideService(deps *Deps) Service {
	return Service{deps}
}

// ProvideAnotherService ...
func ProvideAnotherService(deps *Deps) AnotherService {
	return AnotherService{deps}
}
