// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"time"
)

// Injectors from wire.go:

func InitService() Service {
	mainDeps := ProvideDeps()
	service := ProvideService(mainDeps)
	return service
}

func InitAnotherService() AnotherService {
	mainDeps := ProvideDeps()
	anotherService := ProvideAnotherService(mainDeps)
	return anotherService
}

// wire.go:

// Single Instance
var deps *Deps

// ProvideDeps ...
func ProvideDeps() *Deps {
	if deps != nil {
		return deps
	}

	deps = &Deps{
		date: time.Now(),
	}

	return deps
}

// ProvideService ...
func ProvideService(deps2 *Deps) Service {
	return Service{deps2}
}

// ProvideAnotherService ...
func ProvideAnotherService(deps2 *Deps) AnotherService {
	return AnotherService{deps2}
}
